"# Placeholder Prometheus configuration" 
# Global configuration
global:
  scrape_interval: 15s # How often to scrape targets by default
  evaluation_interval: 15s # How often to evaluate rules

# Scrape configuration
scrape_configs:
  - job_name: 'node-app'
    static_configs:
      - targets: ['node-app:3000'] # Replace with your Node.js app's endpoint

  - job_name: 'python-app'
    static_configs:
      - targets: ['python-app:5000'] # Replace with your Python app's endpoint

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] # Prometheus itself